### ISSUE TITLE
APPLYED - Anotação de configuração para flyway

### ISSUE THREAD

**Issue by githiago-f** [githiago-f/spring-blog#4]
## Anotação - configurando o flyway

```YML
spring:
   jpa:
     hibernate:
       ddl-auto: none
```

adicionar isto para que apenas o flyway gere as entidades no banco de dados.
